// practice/071-ng-lagou/src/app/page/admin/base/base.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-base',
  templateUrl: './base.component.html',
  styleUrls: ['./base.component.css']
})
export class adminBaseComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
<div class="row">
    <div class="col-2">
     <div class="nav flex-column">
       <a routerLink="job" class="nav-link active">招聘管理</a>
       <a routerLink="user" class="nav-link active">用户管理</a>
     </div>
    </div>
    <div class="col-10">
      <router-outlet></router-outlet>
    </div>

  </div>
</div>

// project/013-vue-circle/src/page/admin/Base.vue
<template>
    <div>
        <div class="container">
        <div class="row">
            <div class="col-8 vertical-nav">
                <router-link to="/admin/user">用户管理</router-link>
                <router-link to="/admin/thread">帖子管理</router-link>
            </div>
            <div class="col-16 setting-content">
                <router-view></router-view>
            </div>
        </div>

        </div>
    </div>
</template>
<script>
import '../../css/admin.css'
export default {
    
}
</script>
